<style>
    
    section{margin: 18px 0px;}
    .bill-card {
        width: 245px;
        height: 181px;
        border: 1px solid black;
        /* color: white; */
        font-size: 19px;
        background-color: #ffffff;
        margin: 37px 52px 0px;
    }
   .card .card-header {
        border-bottom: 1px solid black;
        padding: 4px 0px;
    }
    .btn.btn-primary.detail{
        width: 176px; 
         margin: 22px 12px 0px;
    }
    .link.btn.btn-primary{ margin: 17px 37px 0px;}
   .btn.btn-primary{
    display: block;
    width: 115px;
    height: 31px;
    font-size: 16px;
    background: #2563a7;
    border: 1px solid;}
    .btn.btn-primary:hover {background: #2563a7;
        color: #fff;
    } 
    a:link, a:visited {
    color: #fff;}

</style>

<section class="col-lg-12">
    <!-- class="container"> -->
    <div class="box box-success" id="loading-example">
        <div class="box-header">
            <i class="fa fa-th"></i>
            <? $outp = $this->client ?> 
            <h3 class="box-title">Client -<strong><?= $this->escape($outp['client_name'])?></strong></h3>                             
        </div><!-- /.box-header -->
    
        <?php  foreach($this->result as $result) { ?> 
            
             <div class="card bill-card col-lg-4">
                <div class="card-header">
                 <?= substr($this->escape($outp['client_name']), 0, 4)."- ".str_pad($this->escape($result['bill_no']), 3, '0', STR_PAD_LEFT)."/".$this->escape($result['bill_date']);?>
                </div>

                    <?php if($result['status'] == 0){ ?>
                       <div class="btn-mini btn-danger btn-flat"> Pandding</div>
                        <?php }elseif($result['status'] == 1){?>
                        <div class="btn-mini btn-success btn-flat change paystatus ">paid</div>
                    <?php }?>
                
                <div class="card-body">
                    <a class="btn btn-primary detail" href="<?php echo $this->url(array('module'=>'default', 'controller' => 'billstatus', 'action' => 'viewdata', 'bill_no' => $result['bill_no']));?>" target="_blank">View Payment Details<button type="button"></button></a>

                    <a class="link btn btn-primary " href="javascript:;" src="<?php echo $this->url(array('module' => 'default', 'controller' => 'billprint', 'bill' => $result['bill_no']),NULL,TRUE);?>">print Bill<button type="button"></button> </a>

                    
                </div>
            </div> 

        <?php } ?>
    </div>

</section>               
                       	             
<script>
 $(document).ready(function () {

      /**------------- print bill ---------- */
      $('.link').on('click', function () {
            var src = $(this).attr('src');
            $('#myModal').modal('show');
            $('#myModal iframe').attr('src', src);
            $('#myModal .modal-dialog .modal-content .modal-header span').html($(this).attr('a'));
            });
            $('#myModal button').click(function (e) {
                e.preventDefault;
                $('#myModal iframe').removeAttr('src');
            });

        });
</script>