<?php echo "<!DOCTYPE html>"."\n"; ?>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Start your development with a Dashboard for Bootstrap 5.">
	<meta name="author" content="Creative Tim">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
<?php

$this->headTitle("Admincontrol : Billing Software"); 	
$this->headMeta()->appendHttpEquiv('Cache-Control','text/html; charset=utf-8')
								->appendName('description', 'Billing Software')
								->appendName('keywords', 'Billing Software');							
/*css files*/
$this->headLink()->appendStylesheet($this->BaseUrl().'/assets/vendor/nucleo/css/nucleo.css');
$this->headLink()->appendStylesheet($this->BaseUrl().'/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css');
$this->headLink()->appendStylesheet($this->BaseUrl().'/assets/css/argon.css?v=1.1.0');

/* end css */

/*script files */
$this->headScript()->appendFile($this->BaseUrl().'/assets/vendor/jquery/dist/jquery.min.js','text/javascript');
$this->headScript()->appendFile($this->BaseUrl().'/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js','text/javascript');
$this->headScript()->appendFile($this->BaseUrl().'/assets/vendor/js-cookie/js.cookie.js','text/javascript');
$this->headScript()->appendFile($this->BaseUrl().'/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js','text/javascript');
$this->headScript()->appendFile($this->BaseUrl().'/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js','text/javascript');
$this->headScript()->appendFile($this->BaseUrl().'/assets/vendor/chart.js/dist/Chart.min.js','text/javascript');
$this->headScript()->appendFile($this->BaseUrl().'/assets/vendor/chart.js/dist/Chart.extension.js','text/javascript');
$this->headScript()->appendFile($this->BaseUrl().'/assets/js/argon.js?v=1.1.0','text/javascript');
$this->headScript()->appendFile($this->BaseUrl().'/assets/js/demo.min.js','text/javascript');

/*end script */
echo $this->headTitle()."\n";
echo $this->headMeta()."\n";
echo $this->headLink()."\n";
echo $this->headScript()."\n";
?>

</head>
<body class="bg-default">
		<div class="container-fluid">			
			<div class="main-content">
				<!-- Header -->
				<div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
				<div class="container">
					<div class="header-body text-center mb-7">
					<div class="row justify-content-center">
						<div class="col-xl-5 col-lg-6 col-md-8 px-5">
						<h1 class="text-white">Welcome!</h1>
						</div>
					</div>
					</div>
				</div>
				<div class="separator separator-bottom separator-skew zindex-100">
					<svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
					<polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
					</svg>
				</div>
				</div>
				<!-- Page content -->
				<div class="container mt--8 pb-5">
				<div class="row justify-content-center">
					<div class="col-lg-5 col-md-7">
					<div class="card bg-secondary border-0 mb-0">
						<div class="card-body px-lg-5 py-lg-5">
						<div class="text-center text-muted mb-4">
							<small>
								<div class="alert alert-info">
											<?php
											$Session = new Zend_Session_Namespace("ZSN");
											if (isset($Session->ErrorMessage))
											{
													echo $Session->ErrorMessage;
													UNSET($Session->ErrorMessage);
											}
											else{
												echo "Please login with your Username and Password.";
											}
											?>
								</div><?php echo $this->layout()->content; ?>
							</small>
						</div>
						</div>
					</div>
						<div class="row mt-3">
							<div class="col-12">
							<a href="https://treemultisoft.com/" target="_blank" class="text-light"><small>Developed by : Tree Multisoft Services</small></a>
							</div>
						</div>
					</div>
				</div>
				</div>
  			</div>
		</div><!--/.fluid-container-->
</body>
</html>